---
title: "Ressources pédagogiques d'autoformation en Science de données "
description: |
  Langage de prommation R.
author:
  - name: Jeanpierre Hien 
    url: https://example.com/norajones
    affiliation: WASCAL
    affiliation_url: https://example.com/spacelysprokets
  - name: Ousmane Ouedraogo
    url: https://ousmane-ouedraogo.netlify.app/
    affiliation: ANAM
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Contexte

Les progrès scientifiques réalisés dans le domaine des sciences de l'informatique ont conduit à l'avènement d'une nouvelle ère à savoir celle de l'informatique depuis le milieu du XX ème siècle.
Cette nouvelle ère se traduit par un bouleversement au niveau mondial passant d'un monde dominé par une économie traditionnelle à une économie orientée vers le numérique, l'informatique et la technologie.
Dans ce contexte, le développement des compétences dans le domaine de l'informatique s'avère indispensable.
Si au Nord, une avancée notable est observée dans le développement des capacités et des compétences dans les domaines informatiques, la science des données etc., au Sud, ce n'est pas le cas.
Le retard est énorme.
Cet état pourrait se justifier entre autres en partie par le faible niveau d'accès à l'outil informatique mais surtout l'absence d'initiation à l'informatique et à la science des données dans les cursus scolaire et académique.
En effet, très peu de programme universitaire en Afrique subsaharienne offre cet outillage devenu indispensable dans un monde qui requiert de nouvelles compétences.
Pourtant, des opportunités de formation en apprentissage personnalisé existent à travers des ressources gratuites (MOOC, web etc.).
Malheureusement, la méconnaissance de l'accès à ces ressources constitue un facteur limitant à l'auto-formation et l'apprentissage des sciences informatiques.
Or, se former dans les domaines informatiques de nos jours c'est accroître ses compétences et se donner des chances de se positionner sur un marché de l'emploi très dynamique et orienté vers le numérique.
Fort de ce constat, il a été décidé d'apporter une modeste contribution à travers à la production et la vulgarisation des ressources web avec un contenu adapté pour faciliter l'apprentissage. 

## Objectif

L'objectif général visé par la page web est **de produire des contenus rassemblant des ressources web dédiées à la sciences informatique** afin de faciliter l'auto-formation.
 De façon spécifique, il s'agit de 

-    Faciliter l'accès des ressources à des personnes intéressées par la formation en informatique et science des données

-   Contribuer à développer de nouvelles capacités et des compétences des apprenants afin de répondre aux besoins du marché

-   Contribuer à vulgariser et produire du contenu accessible à tous

## Résultats

Les résultats suivants sont visés :

-   Les ressources dédiées à la science informatique en accès
    libre sont disponibles et connues

-   Les personnes ont accès aux ressources web en ligne

-   Le développement de nouvelles compétences en sciences
    informatiques est une réalité

·     
Etc.
